import React from "react";
import { SectionLabel } from "./SectionLabel";

export function EvidencePanel() {
  return (
    <div className="grid grid-cols-1 lg:grid-cols-12 gap-10 items-start py-8">
      {/* Left: Concise Explanation */}
      <div className="lg:col-span-5 space-y-4">
        <SectionLabel>Empirical Record Standards</SectionLabel>
        <h2 className="text-2xl sm:text-3xl font-bold text-navy leading-tight">
          Observational Evidence, Logged Verbatim
        </h2>
        <p className="text-sm text-ink-soft leading-relaxed">
          Every evaluation generated by ASTONTO relies on controlled multi-run testing. We preserve verbatim output logs, citation URLs, and position orders to ensure complete auditability.
        </p>
        <div className="pt-2 text-xs font-mono text-muted space-y-1">
          <p>• 100% Verbatim Output Capture</p>
          <p>• Multi-Platform Run Logs</p>
          <p>• Non-Deterministic Variance Tracking</p>
        </div>
      </div>

      {/* Right: Typeset Research Record Panel */}
      <div className="lg:col-span-7 rounded-2xl bg-surface border border-line p-6 shadow-sm space-y-4 font-mono text-xs text-ink">
        <div className="flex items-center justify-between border-b border-line pb-3">
          <span className="font-bold text-navy uppercase tracking-wider">
            Sample Audit Record #LOG-2026-0842
          </span>
          <span className="px-2 py-0.5 rounded bg-cyan-soft text-cyan-deep font-bold text-[10px]">
            Reliability: High
          </span>
        </div>

        <div className="grid grid-cols-2 gap-3 text-[11px]">
          <div>
            <span className="text-muted block">Platform:</span>
            <span className="font-semibold text-navy">ChatGPT-4o (OpenAI)</span>
          </div>
          <div>
            <span className="text-muted block">Methodology Version:</span>
            <span className="font-semibold text-cyan-deep">PULSE Method v1.0</span>
          </div>
          <div>
            <span className="text-muted block">Location / Language:</span>
            <span className="font-semibold text-navy">London, UK / en-GB</span>
          </div>
          <div>
            <span className="text-muted block">Test Run Iterations:</span>
            <span className="font-semibold text-navy">5 Repeated Runs</span>
          </div>
        </div>

        <div className="pt-2 border-t border-line space-y-1">
          <span className="text-muted block text-[10px] uppercase">Exact Evaluated Prompt:</span>
          <p className="bg-surface-soft p-2.5 rounded text-navy italic font-sans text-xs">
            "Which commercial managed IT service providers in London specialize in financial services security?"
          </p>
        </div>

        <div className="grid grid-cols-2 gap-3 pt-2 text-[11px]">
          <div className="bg-surface-tint p-2.5 rounded border border-cyan/20">
            <span className="text-muted block text-[10px]">Recommendation Class:</span>
            <span className="font-bold text-cyan-deep">Strong Endorsement</span>
          </div>
          <div className="bg-surface-soft p-2.5 rounded border border-line">
            <span className="text-muted block text-[10px]">Sentiment Factor:</span>
            <span className="font-bold text-success">Positive (1.00)</span>
          </div>
        </div>
      </div>
    </div>
  );
}
